server:
  port: 8082

spring:
  application:
    name: account-manag9-auth-service

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com    # можно изменить на smtp.yandex.ru / smtp.mail.ru
    port: 587
    username: ${EMAIL_USERNAME}   # логин почтового ящика
    password: ${EMAIL_PASSWORD}   # пароль приложения (app password)
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
    default-encoding: UTF-8

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000   # 1 час, можно использовать для TTL в Redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
