application:
  name: api-gateway

cloud:
  gateway:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: false
    routes:
      # Auth-service
      - id: auth-service
        uri: lb://ACCAUNT-MANAG9-AUTH-SERVICE
        predicates:
          - Path=/auth/**

      # PhotoResource-service
      - id: photoresource
        uri: lb://ACCAUNT-MANAG9-PHOTORESOURCE-SERVICE
        predicates:
          - Path=/pictures/**                 
        filters:
          # Убираем префикс /pictures, чтобы путь совпадал с контроллером
          - RewritePath=/pictures/(?<segment>.*), /pictures/${segment}

auth:
  public-key:
    path: keys/public.pem  # Публичный ключ auth-service для проверки JWT

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
