spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Маршрут для auth-service
        - id: auth-service
          uri: lb://ACCAUNT-MANAG9-AUTH-SERVICE
          predicates:
            - Path=/auth/**    # проксируем все /auth/** на auth-service

        # Маршрут для resource-service
        - id: photoresource
          uri: lb://ACCAUNT-MANAG9-PHOTORESOURCE-SERVICE
          predicates:
            - Path=/pictures/**          # ловим все запросы /pictures/**
          filters:
            - RewritePath=/pictures/(?<segment>.*), /resource/pictures/${segment}

jwt:
  secret: ${JWT_SECRET}

resource:
  service:
    token: your-internal-token-here

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
