spring:
  application:
    name: client-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: postgres
    password: bestuser
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085

jwt:
  secret: "my-super-long-secret-key-for-hmac-sha256"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
